# Generated by Django 3.0.4 on 2020-05-12 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='pdfs/covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtitle', models.CharField(default='New event', max_length=200, verbose_name='The title of your event')),
                ('day', models.DateField(default=datetime.datetime(2020, 5, 12, 15, 57, 4, 679471, tzinfo=utc), help_text='Use the following format: YYYY-MM-DD', verbose_name='Day of the event')),
                ('start_time', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.TimeField(help_text='Final time', verbose_name='Final time')),
                ('notes', models.TextField(help_text='Textual notes', verbose_name='Textual notes')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=200, verbose_name='the title of a note')),
                ('note_text', models.TextField()),
                ('public_date', models.DateTimeField(default=datetime.datetime(2020, 5, 12, 15, 57, 4, 678427, tzinfo=utc), verbose_name='The publication date')),
            ],
        ),
        migrations.CreateModel(
            name='Tabsettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textcolor', models.CharField(max_length=20, verbose_name='Text color')),
                ('bgcolor', models.CharField(max_length=20, verbose_name='Background color')),
                ('textstyle', models.CharField(max_length=20, verbose_name='Text style')),
                ('fontfamily', models.CharField(max_length=50, verbose_name='Font family')),
                ('fontsize', models.IntegerField(verbose_name='Font size')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=70, verbose_name="The author's name")),
                ('comment_text', models.CharField(max_length=200, verbose_name='The text of a comment')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whynote.Note')),
            ],
        ),
    ]
