# Generated by Django 3.0.4 on 2020-04-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=200, verbose_name='the title of a note')),
                ('note_text', models.TextField()),
                ('public_date', models.DateTimeField(verbose_name='The publication date')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=70, verbose_name="The author's name")),
                ('comment_text', models.CharField(max_length=200, verbose_name='The text of a comment')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whynote.Note')),
            ],
        ),
    ]
