# Generated by Django 3.0.4 on 2020-04-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whynote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('text', models.CharField(max_length=1024, verbose_name='text')),
            ],
        ),
    ]
