# Generated by Django 3.0.4 on 2020-04-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whynote', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=12, max_length=70, verbose_name="The author's name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=12, verbose_name='day of publication'),
            preserve_default=False,
        ),
    ]
