# Generated by Django 3.0.4 on 2020-04-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whynote', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventtitle',
            field=models.CharField(default='New event', max_length=200, verbose_name='The title of your event'),
        ),
    ]
