# Generated by Django 3.0.4 on 2020-04-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whynote', '0003_auto_20200409_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='public_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_title',
            new_name='title',
        ),
    ]
