# Generated by Django 3.0.4 on 2020-04-11 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whynote', '0003_event_eventtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(default=datetime.date(2020, 4, 11), help_text='Use the following format: YYYY-MM-DD', verbose_name='Day of the event'),
        ),
    ]
