# Generated by Django 3.0.4 on 2020-04-11 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whynote', '0004_auto_20200411_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, help_text='Use the following format: YYYY-MM-DD', verbose_name='Day of the event'),
        ),
    ]
