# Generated by Django 3.0.4 on 2020-04-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whynote', '0005_auto_20200411_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabsettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textcolor', models.CharField(max_length=20, verbose_name='Text color')),
                ('bgcolor', models.CharField(max_length=20, verbose_name='Background color')),
                ('textstyle', models.CharField(max_length=20, verbose_name='Text style')),
                ('fontfamily', models.CharField(max_length=50, verbose_name='Font family')),
                ('fontsize', models.IntegerField(max_length=10, verbose_name='Font size')),
            ],
        ),
    ]
